version: 2

sources:
  - name: BV_source
    description: "This is the source for the data Marts comming from the business vault"
    database: taxi_nyc_analytics  
    schema: dbtvault_nyc_schema  
    tables:
      - name: hub_b_payment
        description: "This is the hub for the payment from the business vault"
      - name: link_b_payment_taxi
        description: "This is the link between the payment and taxi from the business vault"
      - name: sat_b_payment
        description: "This is the sat for the payment from the business vault"
      - name: hub_b_tarification
        description: "This is the hub for the tarification from the business vault"
      - name: link_b_tarification_taxi
        description: "This is the link between the tarification and taxi from the business vault"
      - name: sat_b_tarification
        description: "This is the sat for the tarification from the business vault"
      - name: sat_b_zones
        description: "This is the sat for the zones from the business vault"
      - name: sat_b_taxi
        description: "This is the sat for the taxi from the business vault"