version: 2

sources:
  - name: taxi_source
    database: taxi_nyc_database  
    schema: nadim_schema  
    tables:
      - name: payment
      - name: point_of_interest
      - name: tarification
      - name: taxi_vert_nyc
      - name: vendor
      - name: trip
  
  - name: taxi_source_transformed
    database: taxi_nyc_database  
    schema: nadim_transf
    tables:
      - name: zones

models:
  - name: raw_pointOfInterest
    columns:
      - name: placeid
        tests:
          - unique